version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app1:
    build: .
    ports:
      - "12000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/taskdb
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  app2:
    build: .
    ports:
      - "12001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/taskdb
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: